import {useEffect,useRef,useState,FormEvent} from 'react';
import {Gift,Config,defaultConfig,gifts} from '@/lib/catalogue';
import {giftCopy} from '@/lib/gift-copy';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Check,ShoppingBag} from 'lucide-react';
import OrderStatus from './OrderStatus';
import {ApiError,assetUrl,callGiftApi} from '@/lib/api';
type Selection={gift_id:string;gift_name?:string;recipient:string;email:string;phone:string;postal:string;address:string;note:string;status:string;tracking:string;first_submitted_at?:string};
type Stage='detail'|'cart'|'delivery'|'review'|'success';
const empty={recipient:'',email:'',phone:'',postal:'',address:'',note:''};
// Short technical reference shown under service errors, to help the organiser diagnose problems.
const errorRef=(action:string,e:unknown)=>e instanceof ApiError?`Ref: ${action} · ${e.reason}${e.status?' '+e.status:''} · ${e.message}`:`Ref: ${action} · ${e instanceof Error?e.message:'error'}`;
const pickForm=(f:typeof empty)=>({recipient:f.recipient,email:f.email,phone:f.phone,postal:f.postal,address:f.address,note:f.note});
export default function Catalogue(){
 const [lang,setLang]=useState<'en'|'my'>('en'),[config,setConfig]=useState<Config>(defaultConfig),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(''),[category,setCategory]=useState('All gifts');
 const [detail,setDetail]=useState<Gift|null>(null),[cart,setCart]=useState<Gift|null>(null),[panel,setPanel]=useState(false),[stage,setStage]=useState<Stage>('cart'),[code,setCode]=useState(''),[label,setLabel]=useState(''),[verified,setVerified]=useState(''),[form,setForm]=useState(empty),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selection,setSelection]=useState<Selection|null>(null),[emailStatus,setEmailStatus]=useState('');
 const t=giftCopy[lang];
 const ended=!!config.deadline&&Date.now()>new Date(config.deadline+'T23:59:59+09:00').getTime();
 function resetGuest(){setVerified('');setLabel('');setCode('');setPanel(false);setCart(null);setSelection(null);setForm(empty);setConsent(false);setEmailStatus('');setError('');sessionStorage.removeItem('gift-code')}
 function guestError(e:unknown){if(!(e instanceof ApiError))return `${t.serviceError} (${errorRef('request',e)})`;switch(e.reason){case 'not_found':return t.invalidCode;case 'invalid':return t.invalidDetails;case 'locked':return t.cannotChange;case 'closed':return t.closed;case 'ended':return t.ended;case 'unavailable':return t.giftUnavailable;default:return `${t.serviceError} (${errorRef('request',e)})`;}}
 function load(){setLoadError('');callGiftApi<Config>('catalogue').then(d=>{setConfig({...d,gifts:d.gifts.map(g=>({...g,image:assetUrl(g.image)}))});setLoaded(true)}).catch(e=>{console.error('Gift catalogue failed',e);setLoadError(errorRef('catalogue',e))});}
 async function lookup(value=code,showExisting=false){setError('');setBusy(true);const normalized=value.replace(/[\s-]/g,'').toUpperCase();try{const d=await callGiftApi<{label:string;selection:Selection|null}>('lookup',{code:normalized});setCode(normalized);setVerified(normalized);setLabel(d.label);setSelection(d.selection);setEmailStatus('');setConsent(false);setForm(d.selection?pickForm(d.selection):empty);sessionStorage.setItem('gift-code',normalized);if(d.selection){if(showExisting){const g=config.gifts.find(g=>g.id===d.selection!.gift_id)??gifts.find(g=>g.id===d.selection!.gift_id);if(g){setCart(g);setStage('success');setPanel(true)}else setError(t.unavailableGift)}}else if(showExisting){setError(t.noSelection)}}catch(e){if(!verified){resetGuest();setCode(normalized);}setError(guestError(e))}finally{setBusy(false)}}
 const lookupRef=useRef(lookup);lookupRef.current=lookup;
 // A QR card opens …/#code=XXXX. Check it straight away, then remove it from the address bar.
 function cardCode(){const card=/^#code=([A-Za-z0-9]{6,40})$/.exec(window.location.hash);if(card)window.history.replaceState(null,'',window.location.pathname+window.location.search);return card?card[1]:null}
 useEffect(()=>{load();const l=localStorage.getItem('gift-language');if(l==='my')setLang('my');const saved=cardCode()??sessionStorage.getItem('gift-code');if(saved){setCode(saved.toUpperCase());void lookupRef.current(saved)}
  const onHash=()=>{const c=cardCode();if(c){setCode(c.toUpperCase());void lookupRef.current(c)}};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);
 function switchLang(l:'en'|'my'){setLang(l);localStorage.setItem('gift-language',l)}
 function openCart(){setDetail(null);setStage('cart');setPanel(true);setError('')}
 function add(gift:Gift|null=detail){if(!gift||locked)return;setCart(gift);openCart();setConsent(false)}
 async function submit(){if(!cart||!verified||!consent)return;setBusy(true);setError('');try{const d=await callGiftApi<{gift_name?:string;emailStatus?:string;first_submitted_at?:string}>('submit',{code:verified,consent,language:lang,data:{...pickForm(form),gift_id:cart.id}});setSelection({...pickForm(form),gift_id:cart.id,gift_name:d.gift_name,status:'Requested',tracking:'',first_submitted_at:d.first_submitted_at??selection?.first_submitted_at});setEmailStatus(d.emailStatus??'');setStage('success')}catch(e){setError(guestError(e))}finally{setBusy(false)}}
 const [clock,setClock]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer)},[]);
 const locked=!!selection&&(selection.status!=='Requested'||!selection.first_submitted_at||clock>=Date.parse(selection.first_submitted_at)+48*3600000);
 function next(e:FormEvent){e.preventDefault();setStage('review');setError('')}
 const summary=cart&&<div className="selected-summary"><img src={cart.image} alt=""/><div><strong>{cart.brand}</strong><p>{cart.name}</p><p>{lang==='my'?'အရေအတွက် — ၁':'Quantity — 1'}</p></div></div>;
 const headings={detail:detail?.brand??'',cart:t.cart,delivery:t.delivery,review:t.summary,success:t.confirmed};

 const languageSwitch=<button type="button" className="language-toggle" role="switch" aria-checked={lang==='my'} aria-label="Use Burmese language" onClick={()=>switchLang(lang==='en'?'my':'en')}><span lang="en">EN</span><span className="toggle-track" aria-hidden="true"><span/></span><span lang="my">မြန်မာ</span></button>;
 const deadline=<p className="ordering-deadline" role="status">{config.deadline?<>{t.due} <time dateTime={config.deadline}>{new Date(config.deadline+'T00:00:00+09:00').toLocaleDateString(lang==='my'?'my-MM':'en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Tokyo'})}</time>{ended&&<> · {t.ended}</>}</>:t.deadlinePending}</p>;
 const monogram=<div className="invitation-mark"><img src={`${import.meta.env.BASE_URL}branding/monogram.png`} alt="Htoo & May monogram" width="480" height="480"/></div>;
 if(!verified)return <div lang={lang==='my'?'my':'en'} className={lang==='my'?'burmese':''}><div className="site-shell"><header className="masthead"><a className="wordmark" href={import.meta.env.BASE_URL}>Htoo & May</a>{languageSwitch}</header><main className="login-page">{deadline}<section className="login-card">{monogram}<h1>{t.loginTitle}</h1><p>{t.loginIntro}</p><form onSubmit={e=>{e.preventDefault();void lookup()}}><label htmlFor="gift-code">{t.loginId}<input id="gift-code" required autoCapitalize="characters" autoComplete="username" maxLength={40} placeholder={t.code} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><button className="primary full" disabled={busy}>{busy?t.checking:t.enter}</button></form>{error&&<p className="error" role="alert">{error}</p>}<p className="fine">{t.codeHelp}</p></section></main><footer><span>{t.thanks}</span></footer></div></div>;
 return <div lang={lang==='my'?'my':'en'} className={lang==='my'?'burmese':''}><div className="site-shell"><header className="masthead"><a className="wordmark" href={import.meta.env.BASE_URL}>Htoo & May</a><nav><a href="#guide">{t.guideLink}</a><button disabled={busy} onClick={()=>{if(verified)void lookup(verified,true);else document.getElementById('gift-code')?.focus()}}>{t.my}</button><button onClick={openCart}><ShoppingBag size={17} aria-hidden="true"/> {t.cart} ({cart?1:0})</button></nav>{languageSwitch}</header>
 <main>{deadline}<section className="intro">{monogram}<p className="date">16 October 2026</p><h1>{t.title}</h1><p>{t.intro}</p></section>
 <section className="guest-access" aria-label={t.code}>{label?<div className="guest-welcome"><p>{t.welcome}</p><h2>{label}</h2><p>{locked?t.locked:selection?t.savedChoice:t.ready}</p><button className="text-button" disabled={busy} onClick={resetGuest}>{t.switchCode}</button></div>:<form onSubmit={e=>{e.preventDefault();void lookup()}}><label htmlFor="gift-code">{t.code}</label><div className="code-row"><input id="gift-code" required autoCapitalize="characters" autoComplete="off" maxLength={40} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="primary" disabled={busy}>{busy?t.checking:t.check}</button></div><p className="fine">{t.codeHelp}</p></form>}{error&&!panel&&<p className="error" role="alert">{error}</p>}</section>
 {selection&&<OrderStatus order={selection} gift={config.gifts.find(g=>g.id===selection.gift_id)??gifts.find(g=>g.id===selection.gift_id)} language={lang} busy={busy} onRefresh={()=>void lookup(verified)}/>}
 <details id="guide" className="order-guide"><summary>{t.guide}</summary><ol>{t.steps.map((s,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></li>)}</ol></details>
 {!config.open&&loaded&&<div className="draft-note">{t.preview}</div>}
 {loadError?<div className="notice" role="alert"><p>{t.serviceError}</p><p className="fine">{loadError}</p><button className="primary" onClick={load}>{t.retry}</button></div>:<section id="collection" aria-label={t.collection}><div className="filters">{[['All gifts',t.all],['Everyday',t.everyday],['For the table',t.table],['At home',t.home]].map(([c,name])=><button aria-pressed={category===c} className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{name}</button>)}</div><div className="gift-grid">{config.gifts.filter(g=>g.enabled&&(category==='All gifts'||g.category===category)).map((g,i)=><article className={`gift ${cart?.id===g.id?'is-chosen':''}`} key={g.id}><button className="media" aria-label={`${t.view}: ${g.brand} ${g.name}`} onClick={()=>{setDetail(g);setStage('detail');setPanel(true);setError('')}}><img src={g.image} alt={`${g.brand} ${g.name}`} loading={i<3?'eager':'lazy'}/></button><div className="gift-caption"><span className="number">{String(i+1).padStart(2,'0')}</span><div><h2>{g.brand}</h2><p>{g.name}</p></div><div className="gift-actions"><button className="text-button" onClick={()=>{setDetail(g);setStage('detail');setPanel(true);setError('')}}>{t.view}</button><button className="primary" disabled={locked} onClick={()=>add(g)}>{cart?.id===g.id?<><Check size={16} aria-hidden="true"/> {t.added}</>:t.add}</button></div></div></article>)}</div></section>}
 <section className="closing"><h2>{t.one}</h2><p>{t.payment}</p>{config.deadline&&<p>{lang==='my'?'ရွေးချယ်ရန် နောက်ဆုံးရက် — ':'Choose by '}{new Date(config.deadline+'T00:00:00+09:00').toLocaleDateString(lang==='my'?'my-MM':'en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Tokyo'})}</p>}</section></main><footer><span>{t.thanks}</span></footer></div>
 <Dialog open={panel} onOpenChange={o=>{if(!busy){setPanel(o);setError('')}}}><DialogContent className={`gift-dialog ${lang==='my'?'burmese':''}`} lang={lang}><DialogTitle className="dialog-heading">{headings[stage]}</DialogTitle><DialogDescription>{stage==='detail'?detail?.name:label||t.codeHelp}</DialogDescription>
 {stage!=='detail'&&<ol className="checkout-progress" aria-label={t.guide}>{[t.cart,t.delivery,t.review,t.confirmed].map((s,i)=><li key={s} aria-current={['cart','delivery','review','success'][i]===stage?'step':undefined}>{i+1}. {s}</li>)}</ol>}
 {stage==='detail'&&detail&&<><img className="detail-image" src={detail.image} alt={`${detail.brand} ${detail.name}`}/><h3>{detail.description}</h3><p>{detail.details}</p><p className="fine">{t.free}</p><p className="fine">{t.alternative}</p><button className="primary full" disabled={locked} onClick={()=>add()}>{locked?t.locked:t.add}</button></>}
 {stage==='cart'&&<>{cart?<>{summary}<p>{t.one}</p><button className="text-button" onClick={()=>setCart(null)}>{t.remove}</button>{!verified?<><p>{t.codeHelp}</p><form onSubmit={e=>{e.preventDefault();void lookup()}}><label>{t.code}<input required value={code} maxLength={40} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><button className="primary full" disabled={busy}>{busy?t.checking:t.check}</button></form></>:<button className="primary full" disabled={locked} onClick={()=>{setStage('delivery');setConsent(false)}}>{locked?t.locked:t.checkout}</button>}<button className="outline full" onClick={()=>setPanel(false)}>{t.change}</button></>:<><p>{t.empty}</p><button className="primary full" onClick={()=>setPanel(false)}>{t.continue}</button></>}</>}
 {stage==='delivery'&&cart&&<form onSubmit={next} className="delivery-form">{summary}<label>{t.recipient}<input value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value})} required autoComplete="name" maxLength={100}/></label><div className="form-row"><label>{t.email}<input type="email" required autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} maxLength={254}/></label><label>{t.phone}<input type="tel" pattern="\+?[0-9 \(\)\-]{8,25}" required autoComplete="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} maxLength={40}/></label></div><label>{t.postal}<input required inputMode="numeric" autoComplete="postal-code" placeholder="123-4567" pattern="[0-9]{3}-?[0-9]{4}" value={form.postal} onChange={e=>setForm({...form,postal:e.target.value})} maxLength={8}/></label><label>{t.address}<textarea required autoComplete="street-address" minLength={8} maxLength={600} placeholder={t.addressHelp} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>{t.note}<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} maxLength={500}/></label><label className="check-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>{t.consent}</span></label><button className="primary full" disabled={!consent}>{t.review}</button><button type="button" className="outline full" onClick={()=>setStage('cart')}>{t.back}</button></form>}
 {stage==='review'&&cart&&<>{summary}<dl className="order-review">{[[t.recipient,form.recipient],[t.email,form.email],[t.phone,form.phone],[t.postal,form.postal],[t.address,form.address],...(form.note?[[t.note,form.note]]:[])].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl><p className="fine">{t.payment}</p><button className="primary full" disabled={busy||!config.open||ended} onClick={()=>void submit()}>{busy?t.saving:ended?t.ended:!config.open?t.closed:t.confirm}</button><button className="outline full" disabled={busy} onClick={()=>setStage('delivery')}>{t.back}</button></>}
 {stage==='success'&&cart&&<div className="success"><Check size={30}/>{summary}<p>{selection?.status==='Requested'?t.received:t.locked}</p><p>{t.status}: {selection?.status==='Requested'?t.requested:selection?.status==='Ordered'?t.ordered:selection?.status==='Shipped'?t.shipped:selection?.status==='Delivered'?t.delivered:selection?.status}</p>{selection?.tracking&&<p>{t.track}: {selection.tracking}</p>}<p className="fine">{t.keep}</p>{emailStatus&&<p className="fine" role="status">{emailStatus==='sent'?(lang==='my'?'အတည်ပြုအီးမေးလ်ကို ပို့ပြီးပါပြီ။ သင့်အီးမေးလ်နှင့် spam ဖိုင်ကို စစ်ပေးပါ။':'A confirmation email has been sent. Check your inbox and spam folder.'):(lang==='my'?'ရွေးချယ်မှုကို သိမ်းပြီးပါပြီ။ အီးမေးလ်ပို့ဆောင်မှုကို မအတည်ပြုနိုင်သေးပါ။ ထပ်မမှာယူပါနှင့်။':'Your request is saved. Email delivery is not yet confirmed; you do not need to order again.')}</p>}{selection?.status==='Requested'&&!locked&&<button className="outline full" onClick={()=>{setConsent(false);setStage('cart')}}>{t.change}</button>}<button className="primary full" onClick={()=>setPanel(false)}>{t.continue}</button></div>}
 {error&&<p className="error" role="alert">{error}</p>}
 </DialogContent></Dialog></div>;
}
