export type Gift={id:string;brand:string;name:string;category:string;description:string;details:string;image:string;srcSet?:string;source:string;price:number;enabled:boolean};
export const gifts:Gift[]=[
{id:'kinto',brand:'KINTO',name:'Travel tumbler · 500ml',category:'Everyday',description:'A little companion for wherever the day takes you.',details:'An insulated stainless steel travel tumbler. The pictured colour is white.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/kinto.jpg',source:'https://kinto.co.jp/products/20941',price:3520,enabled:false},
{id:'iittala',brand:'iittala',name:'Aino Aalto · two glasses',category:'For the table',description:'Two glasses, for everyday moments worth sharing.',details:'A pair of 220ml Aino Aalto tumblers in clear glass.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/iittala.jpg',source:'https://www.iittala.jp/products/detail/349',price:4400,enabled:false},
{id:'snowpeak',brand:'Snow Peak',name:'Titanium single mug · 450ml',category:'Everyday',description:'For a morning at home, or a weekend somewhere new.',details:'A lightweight, single-wall titanium mug with folding handles. It does not insulate hot drinks.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/snowpeak.jpg',source:'https://ec.snowpeak.co.jp/item/SNP0117A0185',price:3520,enabled:false},
{id:'lecreuset',brand:'Le Creuset',name:'Légère bowl · 500ml',category:'For the table',description:'A beautiful place for something made with love.',details:'One 500ml stoneware bowl in cool mint.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/lecreuset.jpg',source:'https://store.shopping.yahoo.co.jp/lecreuset-japon/lc12439.html',price:3850,enabled:false},
{id:'bodum',brand:'BODUM',name:'BRAZIL French press · 350ml',category:'At home',description:'A slower start, and a very good cup of coffee.',details:'A manual French press coffee maker. Coffee is not included.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/bodum.jpg',source:'https://store.shopping.yahoo.co.jp/bodumshop/10948.html',price:2970,enabled:false},
{id:'towel',brand:'Imabari',name:'Wooden-box face towel pair',category:'At home',description:'A small everyday comfort for your home.',details:'Imabari Kinsei Shifuku towel gift SH55030. Two face towels in a wooden presentation box.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/towel.jpg',source:'https://www.imabari-kinsei.com/c/purpose/purpose2/066SH55030000030',price:3300,enabled:false},
{id:'hario-coffee',brand:'HARIO',name:'Glass brewing kit',category:'At home',description:'A slow morning, made a little more beautiful.',details:'Glass Brewing Kit S-VGBK-02-T. Includes a glass dripper and server, a measuring scoop and 40 paper filters. Coffee is not included.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/hario-coffee.jpg',source:'https://shop.hariocorp.co.jp/products/s-vgbk-02-t',price:3300,enabled:true},
{id:'hario-teapot',brand:'HARIO',name:'Round glass teapot · 700ml',category:'For the table',description:'Something warm to share, one cup at a time.',details:'Cha Cha Kyusu Maru CHJMN-70T. A 700ml heat-resistant glass teapot with a removable stainless steel tea strainer. Tea is not included.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/hario-teapot.jpg',source:'https://shop.hariocorp.co.jp/products/chjmn-70t',price:3300,enabled:true},
{id:'hario-bowls',brand:'HARIO',name:'Lidded glass bowls · pair',category:'At home',description:'For the little things that make a home.',details:'Bowlup BLP-3012-T. Two 1,200ml heat-resistant glass storage bowls with lids.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/hario-bowls.jpg',source:'https://shop.hariocorp.co.jp/products/blp-3012-t',price:3300,enabled:true},
{id:'hario-mug',brand:'HARIO',name:'Tea & coffee brewer mug',category:'Everyday',description:'Your favourite cup, wherever the day begins.',details:'TCM-300-GG-EC in greige, 300ml. Includes the tea and coffee brewing mug and heat-retaining lid. Tea and coffee are not included.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/hario-mug.jpg',source:'https://shop.hariocorp.co.jp/products/tcm-300-gg-ec',price:3300,enabled:true},
{id:'kinto-350-white',brand:'KINTO',name:'Travel tumbler · 350ml · white',category:'Everyday',description:'A favourite drink, wherever the day takes you.',details:'One 350ml insulated stainless steel travel tumbler in white, in a presentation box. Drinks are not included.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/kinto-350-white.jpg',source:'https://shop.benesse.ne.jp/gift/list/item1_0Q/item2_01/item3_01/pro_1410064454/',price:3300,enabled:true},
{id:'kinto-350-khaki',brand:'KINTO',name:'Travel tumbler · 350ml · khaki',category:'Everyday',description:'A little companion for your everyday adventures.',details:'One 350ml insulated stainless steel travel tumbler in khaki, in a presentation box. Drinks are not included.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/kinto-350-khaki.jpg',source:'https://shop.benesse.ne.jp/gift/list/item1_0Q/item2_01/item3_01/pro_1410064455/',price:3300,enabled:true},
{id:'imabari-wooden-blue',brand:'Imabari Kinsei',name:'Wooden-box towel set · blue',category:'At home',description:'A soft everyday comfort, beautifully presented.',details:'Monori towel set J in blue: one 60 × 110cm bath towel and one 31 × 33.5cm wash towel, 100% cotton, made in Japan. Presented in a wooden box.',image:'https://htoo-may-gift-edit.the-studioeternelle.chatgpt.site/products/imabari-wooden-blue.jpg',source:'https://shop.benesse.ne.jp/gift/list/item1_0O/item2_01/item3_01/pro_1410053669/',price:3300,enabled:true}];
export type Config={open:boolean;deadline:string;message:string;gifts:Gift[]};
export const defaultConfig:Config={open:false,deadline:'2027-01-16',message:'Thank you for being part of our story. Please choose one gift with our love.',gifts};
